### ISSUE TITLE
最大内存1MB？

### ISSUE THREAD

**Issue by cctv1005s** [QingdaoU/JudgeServer#28]
填写max_memory 超过 1073741824 （1MB）就会报错

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/code/judge_client.py", line 18, in _run
    return instance._judge_one(test_case_file_id)
  File "/code/judge_client.py", line 122, in _judge_one
    memory_limit_check_only=self._run_config.get("memory_limit_check_only", 0))
  File "/usr/local/lib/python3.5/dist-packages/_judger/__init__.py", line 84, in run
    return json.loads(out.decode("utf-8"))
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/server.py", line 142, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 100, in judge
    run_result = judge_client.run()
  File "/code/judge_client.py", line 165, in run
    result.append(item.get())
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2019-04-10 15:25:42,665 ERROR Expecting value: line 1 column 1 (char 0)
multiprocessing.pool.RemoteTraceback:

```

**Comment by cctv1005s** [comment]
closed
