### ISSUE TITLE
api 请求包错

### ISSUE THREAD

**Issue by cute-angelia** [QingdaoU/JudgeServer#30]
![image](https://user-images.githubusercontent.com/26561606/62026594-05512100-b20e-11e9-949d-5b16d2dc69d4.png)

日志:
```
2019-07-29 06:33:59,805 ERROR 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/code/server.py", line 192, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 68, in judge
    compile_config = language_config.get("compile")
AttributeError: 'str' object has no attribute 'get'

```

看日志, 应该是传入 参数问题
```
	"language_config": "py3_lang_config",
```

看了 client/Python/languages.py 确实是这个

**Comment by virusdefender** [comment]
py3_lang_config 不是一个字符串吧，再仔细看下 client 的代码
