### ISSUE TITLE
提交带有中文的代码会SE，但是我在qdoj.com提交就没问题？

### ISSUE THREAD

**Issue by wang-peijun** [QingdaoU/JudgeServer#45]
```2020-12-01 05:57:08,917 ERROR 'utf-8' codec can't decode byte 0xe4 in position 99: invalid continuation byte
Traceback (most recent call last):
  File "/code/server.py", line 213, in server
    ret = {"err": None, "data": getattr(JudgeServer, path)(**data)}
  File "/code/server.py", line 120, in judge
    output_dir=submission_dir)
  File "/code/compiler.py", line 39, in compile
    error = f.read().strip()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 99: invalid continuation byte```

**Comment by yyy1004** [comment]
修改过代码导致
可能添加了打印 中文提示

**Comment by mikucat0309** [comment]
正在整理 issue 與 PR，有需要再重新打開或開新的 issue 吧。
